@startuml

title __COMPONENT's Class Diagram__\n

  package org.pmesmeur.sketchit {
    package org.pmesmeur.sketchit.diagram {
      package org.pmesmeur.sketchit.diagram.component {
        class ComponentDiagramGenerator {
            - patternsToExclude : java.util.List<java.lang.String>
            - managedModules : java.util.Set<com.intellij.openapi.module.Module>
            {static} + newBuilder()
            # ComponentDiagramGenerator()
            - computeManagedModuleList()
            - excluded()
            - excluded()
            + generate()
            - getListOfManagedModulesOrderedAlphabetically()
            - printModuleDependencies()
        }
      }
    }
  }
  

  package org.pmesmeur.sketchit {
    package org.pmesmeur.sketchit.diagram {
      package org.pmesmeur.sketchit.diagram.component {
        class Builder {
            - patternsToExclude : java.util.List<java.lang.String>
            + Builder()
            + exclude()
            + build()
            + title()
        }
      }
    }
  }
  

  package org.pmesmeur.sketchit {
    package org.pmesmeur.sketchit.diagram {
      package org.pmesmeur.sketchit.diagram.component {
        class ModuleComparator {
            + compare()
        }
      }
    }
  }
  

  package org.pmesmeur.sketchit {
    package org.pmesmeur.sketchit.diagram {
      package org.pmesmeur.sketchit.diagram.component {
        class ModulesHierarchyGenerator {
            - modulePaths : java.util.List<org.pmesmeur.sketchit.diagram.component.ModulesHierarchyGenerator.ModulePath>
            ~ modulePathsDone : java.util.Set<org.pmesmeur.sketchit.diagram.component.ModulesHierarchyGenerator.ModulePath>
            + ModulesHierarchyGenerator()
            - buildModulePaths()
            - buildModulePathsDependencies()
            + generate()
            - generate()
        }
      }
    }
  }
  

  package org.pmesmeur.sketchit {
    package org.pmesmeur.sketchit.diagram {
      package org.pmesmeur.sketchit.diagram.component {
        class ModulePath {
            + subModules : java.util.ArrayList<org.pmesmeur.sketchit.diagram.component.ModulesHierarchyGenerator.ModulePath>
            - ModulePath()
            - getModuleFilePath()
        }
      }
    }
  }
  

  package org.pmesmeur.sketchit {
    package org.pmesmeur.sketchit.diagram {
      package org.pmesmeur.sketchit.diagram.component {
        class ModulePathComparator {
            + compare()
        }
      }
    }
  }
  

  ComponentDiagramGenerator o-- PlantUmlWriter : plantUmlWriter
  ComponentDiagramGenerator o-- Project : project
  ComponentDiagramGenerator o-- String : title
  ComponentDiagramGenerator +-right- Builder
  ComponentDiagramGenerator +-right- ModuleComparator
  Builder o-- PlantUmlWriter : plantUmlWriter
  Builder o-- Project : project
  Builder o-- String : title
  ModuleComparator -up-|> Comparator
  ModulesHierarchyGenerator +-right- ModulePath
  ModulesHierarchyGenerator +-right- ModulePathComparator
  ModulePath o-- Module : module
  ModulePath o-- String : path
  ModulePathComparator -up-|> Comparator


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
