@startuml

title __SKETCHIT's Class Diagram__\n

  package org.pmesmeur.sketchit {
    package org.pmesmeur.sketchit.diagram {
      package org.pmesmeur.sketchit.diagram.clazz {
        class ClassDiagramGenerator {
        }
      }
    }
  }
  

  package org.pmesmeur.sketchit {
    package org.pmesmeur.sketchit.diagram {
      package org.pmesmeur.sketchit.diagram.component {
        class ComponentDiagramGenerator {
        }
      }
    }
  }
  

  package org.pmesmeur.sketchit {
    package org.pmesmeur.sketchit.diagram {
      package org.pmesmeur.sketchit.diagram.clazz {
        class Finder {
        }
      }
    }
  }
  

  package org.pmesmeur.sketchit {
    package org.pmesmeur.sketchit.diagram {
      class JavaFileFinder {
      }
    }
  }
  

  package org.pmesmeur.sketchit {
    package org.pmesmeur.sketchit.diagram {
      package org.pmesmeur.sketchit.diagram.component {
        class ModulesHierarchyGenerator {
        }
      }
    }
  }
  

  package org.pmesmeur.sketchit {
    package org.pmesmeur.sketchit.diagram {
      package org.pmesmeur.sketchit.diagram.plantuml {
        class PlantUmlWriter {
        }
      }
    }
  }
  

  package org.pmesmeur.sketchit {
    class SketchIt {
    }
  }
  

  package org.pmesmeur.sketchit {
    package org.pmesmeur.sketchit.diagram {
      class UmlComponentDiagram {
      }
    }
  }
  

  package org.pmesmeur.sketchit {
    package org.pmesmeur.sketchit.diagram {
      abstract class UmlDiagram {
      }
    }
  }
  

  package org.pmesmeur.sketchit {
    package org.pmesmeur.sketchit.diagram {
      class UmlDiagramsGenerator {
      }
    }
  }
  

  package org.pmesmeur.sketchit {
    package org.pmesmeur.sketchit.diagram {
      class UmlModuleClassDiagram {
      }
    }
  }
  

  package org.pmesmeur.sketchit {
    package org.pmesmeur.sketchit.diagram {
      class UmlSourceDirectoryClassDiagram {
      }
    }
  }
  

  ClassDiagramGenerator o-- PlantUmlWriter : plantUmlWriter
  ClassDiagramGenerator o-- Project : project
  ClassDiagramGenerator o-- Module : module
  ClassDiagramGenerator o-- VirtualFile : sourceDirectory
  ClassDiagramGenerator o-- String : title
  ComponentDiagramGenerator o-- PlantUmlWriter : plantUmlWriter
  ComponentDiagramGenerator o-- Project : project
  ComponentDiagramGenerator o-- String : title
  Finder o-- Project : project
  Finder o-- Module : module
  JavaFileFinder o-- Project : project
  JavaFileFinder o-- Module : module
  PlantUmlWriter o-- OutputStream : outputStream
  SketchIt -up-|> AnAction
  UmlComponentDiagram -up-|> UmlDiagram
  UmlComponentDiagram o-- Project : project
  UmlDiagramsGenerator o-- Project : project
  UmlModuleClassDiagram -up-|> UmlDiagram
  UmlModuleClassDiagram o-- Project : project
  UmlModuleClassDiagram o-- Module : module
  UmlSourceDirectoryClassDiagram -up-|> UmlDiagram
  UmlSourceDirectoryClassDiagram o-- Project : project
  UmlSourceDirectoryClassDiagram o-- Module : module
  UmlSourceDirectoryClassDiagram o-- VirtualFile : moduleDirectory


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
