@startuml

title __CLAZZ's Class Diagram__\n

package org.pmesmeur.sketchit {
package org.pmesmeur.sketchit.diagram {
package org.pmesmeur.sketchit.diagram.clazz {
class Finder {
  - classes : java.util.Set<com.intellij.psi.PsiClass>
  - packages : java.util.Set<java.lang.String>
  - patternsToExclude : java.util.List<java.lang.String>
  + Finder()
  + getClasses()
  + getPackages()
  - findClasses()
  - computeManagedPsiClassesFromFiles()
  - recordFilePackageAsKnownPackage()
  - isTestFile()
  - excluded()
}
}
}
}


package org.pmesmeur.sketchit {
package org.pmesmeur.sketchit.diagram {
package org.pmesmeur.sketchit.diagram.clazz {
class ClassDiagramGenerator {
  - managedClasses : java.util.Set<com.intellij.psi.PsiClass>
  - patternsToExclude : java.util.List<java.lang.String>
  - packages : java.util.List<java.lang.String>
  {static} + newBuilder()
  # ClassDiagramGenerator()
  - createListOfClassesToManage()
  - filterClasses()
  + generate()
  - declareClass()
  - computePackageStack()
  - declareClassMembers()
  - declareClassAttributes()
  - typeBelongsToCurrentProject()
  - typeContainsGeneric()
  - declareClassField()
  - getVisibility()
  - declareClassMethods()
  - declareClassMethod()
  - declareClassRelationships()
  - declareClassInheritence()
  - superClassIsObject()
  - declareClassAssociations()
}
}
}
}


Finder o-- Project : project
Finder o-- Module : module
ClassDiagramGenerator o-- PlantUmlWriter : plantUmlWriter
ClassDiagramGenerator o-- Project : project
ClassDiagramGenerator o-- Module : module
ClassDiagramGenerator o-- VirtualFile : sourceDirectory
ClassDiagramGenerator o-- String : title

right footer
PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
