@startuml

title __DIAGRAM's Class Diagram__\n

  package org.pmesmeur.sketchit {
    package org.pmesmeur.sketchit.diagram {
      class JavaFileFinder {
          - javaFiles : java.util.List<com.intellij.psi.PsiJavaFile>
          - directories : java.util.Set<com.intellij.openapi.vfs.VirtualFile>
          + JavaFileFinder()
          + getFoundFiles()
          + getFoundDirectories()
          - find()
          - findFiles()
          - psiFileBelongsToCurrentModule()
      }
    }
  }
  

  package org.pmesmeur.sketchit {
    package org.pmesmeur.sketchit.diagram {
      class UmlComponentDiagram {
          + UmlComponentDiagram()
          # getOutputFile()
          # generateDiagram()
          - getDiagramGeneratorBuilder()
      }
    }
  }
  

  package org.pmesmeur.sketchit {
    package org.pmesmeur.sketchit.diagram {
      abstract class UmlDiagram {
          + generate()
          {abstract} # getOutputFile()
          - generateDiagram()
          {abstract} # generateDiagram()
          - deleteEmptyFile()
          # createOutputFileName()
      }
    }
  }
  

  package org.pmesmeur.sketchit {
    package org.pmesmeur.sketchit.diagram {
      class UmlDiagramsGenerator {
          + UmlDiagramsGenerator()
          + generateComponentDiagram()
          + generateClassDiagrams()
          - generateModuleClassDiagram()
          - generateModuleClassDiagramForEachSourceDirectory()
          - generateModuleClassDiagramForSourceDirectory()
      }
    }
  }
  

  package org.pmesmeur.sketchit {
    package org.pmesmeur.sketchit.diagram {
      class UmlModuleClassDiagram {
          + UmlModuleClassDiagram()
          # getOutputFile()
          - getClassDiagramOutputStream()
          # generateDiagram()
          - getDiagramGeneratorBuilder()
      }
    }
  }
  

  package org.pmesmeur.sketchit {
    package org.pmesmeur.sketchit.diagram {
      class UmlSourceDirectoryClassDiagram {
          + UmlSourceDirectoryClassDiagram()
          # getOutputFile()
          # generateDiagram()
          - getDiagramGeneratorBuilder()
      }
    }
  }
  

  JavaFileFinder o-- Project : project
  JavaFileFinder o-- Module : module
  UmlComponentDiagram -up-|> UmlDiagram
  UmlComponentDiagram o-- Project : project
  UmlDiagramsGenerator o-- Project : project
  UmlModuleClassDiagram -up-|> UmlDiagram
  UmlModuleClassDiagram o-- Project : project
  UmlModuleClassDiagram o-- Module : module
  UmlSourceDirectoryClassDiagram -up-|> UmlDiagram
  UmlSourceDirectoryClassDiagram o-- Project : project
  UmlSourceDirectoryClassDiagram o-- Module : module
  UmlSourceDirectoryClassDiagram o-- VirtualFile : moduleDirectory


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
